# Generated by Django 3.2.4 on 2022-05-10 15:29

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.FloatField(validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
                ('latitude', models.FloatField(validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Operation2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_frequency', models.IntegerField(default=1)),
                ('last_collection', models.DateTimeField(default=datetime.datetime.now)),
                ('bin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='op2', to='evrkapp.bin')),
            ],
        ),
        migrations.CreateModel(
            name='Operation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_frequency', models.IntegerField(default=1)),
                ('last_collection', models.DateTimeField(default=datetime.datetime.now)),
                ('bin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='op1', to='evrkapp.bin')),
            ],
        ),
        migrations.CreateModel(
            name='Navigationrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
                ('latitude', models.FloatField(validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evrkapp.vehicle')),
            ],
        ),
        migrations.AddIndex(
            model_name='navigationrecord',
            index=models.Index(fields=['vehicle', 'datetime'], name='evrkapp_nav_vehicle_b30269_idx'),
        ),
    ]
